# Generated by Django 4.2.4 on 2023-09-08 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='updated_at',
        ),
    ]
