# Generated by Django 4.2.4 on 2023-09-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_remove_follow_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image_url",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="is_hidden",
            field=models.BooleanField(default=False),
        ),
    ]
