# Generated by Django 4.2.4 on 2023-09-18 04:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_post_image_url_post_is_hidden"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
