name: CD

on:
    workflow_run:
      workflows: ["CI"]
      types:
        - completed
    push:
        tags:
          - "*.*.*"
        branches:
          - 'main'
        paths:
          - '.github/workflows/**'
          - 'trackproject/**'
 
env:
    IMAGE_TAG: ${{ vars.NCR_REGISTRY }}/trackmission:latest


jobs:
    deploy:
        name: deploy
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        steps:
        - name: checkout
          uses: actions/checkout@v3

        - name: change apiVersion
          if: startsWith(github.ref, 'refs/tags')
          run: |
            cd k8s/trackmission/
            sed -i 's/appVersion: ".*"/appVersion: "${{ github.ref_name }}"/g' Chart.yaml
            cat Chart.yaml
            git add .
            git config --global user.email "hjklo0220@gmail.com"
            git config --global user.name "JunYoung_Kim"
            git commit -m "change apiVersion in actions"
            git push

        - name: server access
          uses: appleboy/ssh-action@v1.0.0
          with:
            host: ${{ secrets.BACKEND_IP }}
            username: ${{ secrets.USERNAME }}
            password: ${{ secrets.PASSWORD }}
            script: |
                docker login ${{ vars.NCR_REGISTRY }} \
                -u ${{ secrets.NCR_ACCESS_KEY }} -p ${{ secrets.NCR_SECRET_KEY }}
                docker pull ${{ env.IMAGE_TAG }}
                docker stop trackmission && docker rm trackmission
                docker run -p 8000:8000 -d \
                --env-file /home/lion/.env \
                --name trackmission \
                devpos6th.kr.ncr.ntruss.com/trackmission:latest
