name: CI

on:
    pull_request:
    push:
        tags:
          - "*.*.*"
        # branches:
        #     - 'main'
        # paths:
        #     - '.github/workflows/**'
        #     - 'trackproject/**'

env:
    IMAGE: ${{ vars.NCR_REGISTRY }}/trackmission
    IMAGE_TAG: ${{ vars.NCR_REGISTRY }}/trackmission:latest

jobs:
    lint:
        name: check lint (black)
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: setup python
              uses: actions/setup-python@v4
              with:
                python-version: '3.11'
            - name: install black
              run: pip install black
            - name: check black
              run: black trackproject
            


    build-test-push:
        needs: lint
        name: build-push
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: test
              run: |
                docker build -t track:test trackproject/
                export DB_HOST=${{ secrets.DB_HOST }}
                docker run --name track-test -p 8000:8000 -d --env-file .envs/local/django track:test
                docker exec track-test python manage.py test

            - name: set up docker buildx
              uses: docker/setup-buildx-action@v2
            
            - name: Login to NCR
              uses: docker/login-action@v2
              with:
                registry: ${{ vars.NCR_REGISTRY }}
                username: ${{ secrets.NCR_ACCESS_KEY }}
                password: ${{ secrets.NCR_SECRET_KEY }}

            - name: Get current timestamp
              id: timestamp
              run: echo "timestamp=$(date '+%s')" >> "$GITHUB_OUTPUT"

            - name: bulid and push refs/heads
              if: startsWith(github.ref, 'refs/heads')
              uses: docker/build-push-action@v4
              with:
                  context: trackproject
                  tags: ${{ env.IMAGE_TAG }},"${{ env.IMAGE }}:${{ steps.timestamp.outputs.timestamp }}"
                  push: true

            - name: bulid and push refs/tags
              if: startsWith(github.ref, 'refs/tags')
              uses: docker/build-push-action@v4
              with:
                  context: trackproject
                  tags: ${{ env.IMAGE_TAG }},"${{ env.IMAGE }}:${{ github.ref_name }}"
                  push: true
